# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='tempLogging',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\x12\x0btempLogging\"E\n\x12TempLoggingRequest\x12\x0c\n\x04temp\x18\x01 \x01(\x01\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x05\x12\x10\n\x08humidity\x18\x03 \x01(\x01\"\x15\n\x13TempLoggingResponse2]\n\x0bTempLogging\x12N\n\x07LogTemp\x12\x1f.tempLogging.TempLoggingRequest\x1a .tempLogging.TempLoggingResponse\"\x00\x62\x06proto3'
)




_TEMPLOGGINGREQUEST = _descriptor.Descriptor(
  name='TempLoggingRequest',
  full_name='tempLogging.TempLoggingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp', full_name='tempLogging.TempLoggingRequest.temp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='tempLogging.TempLoggingRequest.channel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='tempLogging.TempLoggingRequest.humidity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=99,
)


_TEMPLOGGINGRESPONSE = _descriptor.Descriptor(
  name='TempLoggingResponse',
  full_name='tempLogging.TempLoggingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['TempLoggingRequest'] = _TEMPLOGGINGREQUEST
DESCRIPTOR.message_types_by_name['TempLoggingResponse'] = _TEMPLOGGINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TempLoggingRequest = _reflection.GeneratedProtocolMessageType('TempLoggingRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPLOGGINGREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:tempLogging.TempLoggingRequest)
  })
_sym_db.RegisterMessage(TempLoggingRequest)

TempLoggingResponse = _reflection.GeneratedProtocolMessageType('TempLoggingResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEMPLOGGINGRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:tempLogging.TempLoggingResponse)
  })
_sym_db.RegisterMessage(TempLoggingResponse)



_TEMPLOGGING = _descriptor.ServiceDescriptor(
  name='TempLogging',
  full_name='tempLogging.TempLogging',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=124,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='LogTemp',
    full_name='tempLogging.TempLogging.LogTemp',
    index=0,
    containing_service=None,
    input_type=_TEMPLOGGINGREQUEST,
    output_type=_TEMPLOGGINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPLOGGING)

DESCRIPTOR.services_by_name['TempLogging'] = _TEMPLOGGING

# @@protoc_insertion_point(module_scope)
